---
openapi: 3.0.0
info:
  title: API User V1
  description: Realiza el mantenimiento (CRUD) de los usuarios
  version: 1.0.0
servers:
  - url: /api/v1/users
paths:
  /:
    post:
      tags:
        - Create User
      summary: Habilita nuevos usuarios
      description: |
        Realiza la creacion de un nuevo usuario
      operationId: registerUser
      requestBody:
        description: Input
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        "201":
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        "400":
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiException'
components:
  schemas:
    UserRequest:
      required:
        - email
        - name
        - password
      type: object
      properties:
        name:
          maxLength: 50
          pattern: "^[A-Za-zÁÉÍÓÚÑáéíóúñ\\s]+$"
          type: string
          description: Nombre
          example: Jean Herrera
        email:
          pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
          type: string
          description: Correo electrónico
          example: example@gmail.com
        password:
          maxLength: 50
          type: string
          description: "Clave de usuario (debe contener mayúscula, minúscula, digitos, caracter especial)"
          example: Apple
        phones:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
    Phone:
      type: object
      properties:
        number:
          type: string
          pattern: "^[\\d]{7,15}$"
          description: Número
          example: "999999999"
        cityCode:
          pattern: "^[\\d]{1,3}$"
          type: string
          description: Código de ciudad
          example: "1"
        countryCode:
          pattern: "^[\\d]{1,3}$"
          type: string
          description: Código de país
          example: "57"
    UserResponse:
      type: object
      properties:
        id:
          type: string
          description: Identificador
          example: "588"
        created:
          type: string
          description: Fecha de creacion
          example: 20-01-2024
        modified:
          type: string
          description: Fecha de ultima modificacion
          example: 20-01-2024
        lastLogin:
          type: string
          description: Ultimo ingreso
          example: 20-01-2024
        token:
          type: string
          description: Token de acceso
        isActive:
          type: boolean
          description: Usuario activo
          example: true
    ApiException:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error
          example: Error
